

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    image: aljazeera-tests
    volumes:
      - ./target/allure-results:/app/target/allure-results
      - ./target/allure-report:/app/target/allure-report

    environment:
      MAILSLURP_API_KEY: ${MAILSLURP_API_KEY}
      DOCKER: "true"
    command: >
      sh -c "
        xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' mvn test &&
        allure generate target/allure-results -o target/allure-report --clean
      "
