version: '3.8'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    image: aljazeera-tests
    volumes:
      - ./target/allure-results:/app/target/allure-results
    environment:
      MAILSLURP_API_KEY: ${MAILSLURP_API_KEY}
      DOCKER: "true"
    command: >
      sh -c "xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' mvn test"
