version: '3.8'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    # Force linux/amd64 if needed (useful on ARM Macs)
    platform: linux/amd64

    image: aljazeera-tests

    volumes:
      # Cache Maven dependencies between runs (huge speed-up!)
      - ~/.m2:/root/.m2

      # Save allure results & reports on the host machine
      - ./target/allure-results:/app/target/allure-results
      - ./target/allure-report:/app/target/allure-report

    environment:
      MAILSLURP_API_KEY: ${MAILSLURP_API_KEY}
      DOCKER: "true"

    command: >
      sh -c "
        google-chrome --version &&
        xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' google-chrome --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 & sleep 3 &&
        echo '✅ Chrome started OK' &&
        xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' mvn test -Dsurefire.threadCount=1 &&
        allure generate target/allure-results -o target/allure-report --clean
      "


    ports:
      # Map container's 8080 -> host's 9090 (to avoid conflict with Jenkins)
      - "9090:8080"

    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G



